### ISSUE TITLE
When element height matches document height does not scroll.

### ISSUE THREAD

**Issue by erfanio** [gblazex/smoothscroll#105]
This problem is recreated [here](http://codepen.io/atrotors/pen/eNRaow) but it doesn't work in frame so you can test this problem in the [fullscreen preview](http://s.codepen.io/atrotors/debug/eNRaow?).
The problem is from the if statement in line 558. I would create a pull request but I am not sure I 100% grasp your logic so I don't want to mess with it.

**Comment by galambalazs** [comment]
Thanks, I'll look into this.
