### ISSUE TITLE
It's just a wish, I'm too lazy to do pull request

### ISSUE THREAD

**Issue by DenVdmj** [gblazex/smoothscroll#128]
It's just a wish, and seems to me that for such a trifle isn`t worth doing pull request.

1) get_manifest in options.js: maybe it can look a little bit easier:
`byId('version').textContent = chrome.runtime.getManifest().version;`
`byId('version').textContent = chrome.app.getDetails().version;`

2) requestFrame and cancelFrame in sscr.js: maybe it can look a little bit easier: 

```
var requestFrame =
    window.requestAnimationFrame ||
    window.webkitRequestAnimationFrame ||
    function (callback, element, delay) {
      setTimeout(callback, delay || (1000/60));
    }
;
```

And thank you so much for the excellent extension.

**Comment by galambalazs** [comment]
Yes thanks for reminding me. App version now has APIs from Google.
As for RAF I think the whole thing can be removed now.
Chrome has been supporting the non-prefixed version since 24+
