### ISSUE TITLE
Scrolling up and down results in "Net Scrolling" going up.

### ISSUE THREAD

**Issue by HatsuneVocaloidMiku** [gblazex/smoothscroll#139]
Sorry as I have no other idea for a better title.

If I scroll up and down repeatedly, the result is that I will be slowly going up as it seems that the scrolling up step size is somehow more than scrolling down.

**Comment by gblazex** [comment]
what is your step size. 1-2 px difference is possible, but nothing more than that

**Comment by ghost** [comment]
Sorry, it's been forever since I've used this. I've given up on it since.
