### ISSUE TITLE
Add "back" and "forward" touchpad gestures

### ISSUE THREAD

**Issue by MaluNoPeleke** [gblazex/smoothscroll#142]
Feature request:

Please add "back" and "forward" two finger swipe touchpad gesture support.

**Comment by galambalazs** [comment]
Mac?

**Comment by MaluNoPeleke** [comment]
No, Windows 10

**Comment by JonathanCasey** [comment]
I worked around this in Windows 10 by following [this](https://www.addictivetips.com/windows-tips/three-finger-swipe-for-browser-navigation-windows-10/) to set my forward/back navigation to use 3-finger swipe.

**Comment by gblazex** [comment]
hey guys, I don't know if it can be fixed. im guessing it's with Touchpad support ON? because with Off I don't see this issue

**Comment by gblazex** [comment]
please comment in #59 as they are the same
