### ISSUE TITLE
Horizontal scrolling (Shift+mousewheel) not working in Chrome

### ISSUE THREAD

**Issue by dullahan8** [gblazex/smoothscroll#148]
Normally, it is possible to scroll wide webpages horizontally by using the mousewheel while holding Shift on the keyboard. In more recent iterations of this Smoothscroll extension, the horizontal functionality has not been working in Chrome browser. Disabling the extension restores horizontal scrolling function.

**Comment by gblazex** [comment]
is it linux?

**Comment by raphtlw** [comment]
Yup, experiencing the same issue too on Windows 10, Google Chrome Version 77. Surface Laptop 2

**Comment by jtbrown3** [comment]
I was so sad to discover that this, otherwise great, extension 'disables' Chrome's horizontal scrolling feature (shift+mousewheel).  Tweaking the setting and disabling keyboard support does not help.  Such a shame!

@gblazex, can you please fix this?

**Comment by gblazex** [comment]
which OS? it works for me. always have

**Comment by vith** [comment]
Just checked it now in a new Chrome profile on Windows 10, doesn't work. It just scrolls vertically instead of horizontally while holding shift whenever this extension is enabled.

**Comment by vith** [comment]
On Arch Linux + Chromium there is no problem.

**Comment by jtbrown3** [comment]
> which OS? it works for me. always have

@gblazex  Windows 10 - Horizontal scrolling fails on all 3 of my Chrome-based browsers (Chrome, Brave, Edge Chromium) when this extension gets loaded.  Many others are also reporting this and it happens on fresh chrome profiles that have no other potentially interfering extensions loaded.  Please address this, Blaze.

**Comment by brian6932** [comment]
@gblazex This issue still exists, it's extremely annoying
For reference I'm on windows 10
