### ISSUE TITLE
Can't scroll up on Twitter profiles

### ISSUE THREAD

**Issue by AdamEC** [gblazex/smoothscroll#151]
With the extension enabled, the scrollbar will automatically go back before reaching the top of the profile, creating a loop and never being able to reach the top of the page.

Using the physical scrollbar on the side will work, including disabling the extension or blacklisting the site.

**Comment by EatZeBaby** [comment]
Same issue with default values. Blacklisted twitter in the meantime.

**Comment by gblazex** [comment]
works for me in the update version, feel free to comment/reopen if you find it still happening
