### ISSUE TITLE
Stops scrolling over youtube expandos on reddit

### ISSUE THREAD

**Issue by misternop** [gblazex/smoothscroll#156]
Go to reddit. Irrelevant if you use RES extension or not. Find a video post and expand it. Scroll wont work when you mouse over expando.

EDIT: It doesn't stop completely, just the effect of smooth scroll this extension does stops.

**Comment by vitaly-zdanevich** [comment]
I confirm that - soft scrolling do not works when mouse hover youtube video, not only on Reddit, for example here too https://jakearchibald.com/2016/sounds-fun/

**Comment by 14u2ponder** [comment]
Any video you scroll over it seems has the problem. It works better in netflix thoug and hulu seems fine.

**Comment by gblazex** [comment]
looks good to me in the latest version. feel free to comment/reopen if you feel like you need to guys ;)
