### ISSUE TITLE
Stops scrolling on https://icons8.com

### ISSUE THREAD

**Issue by misternop** [gblazex/smoothscroll#157]
Example page https://icons8.com/icon/new-icons/all

Scroll will only work if mouseover the actual scroll bar on page and not over the area that is supposed to be scrolled. If extension is disabled scroll works.

**Comment by visualpharm** [comment]
We've rewritten Icons8 from scratch, have a look?

**Comment by misternop** [comment]
@visualpharm thx, Icons8 now seems to smooth scroll properly using this extension. Good job!

**Comment by abdulbadii** [comment]
Another one not work on:
https://blazepress.com/2016/02/24-pictures-that-will-completely-mess-with-your-head/
Anyone figure it out?

**Comment by gblazex** [comment]
it's fixed in the latest version
