### ISSUE TITLE
Home key scroll doesn't work after recent chrome update

### ISSUE THREAD

**Issue by iori3000** [gblazex/smoothscroll#158]
Home key scrolling doesn't work after last updating of chrome 61.0.3163.79

**Comment by gitarian** [comment]
Confirmed with Vivaldi snapshot 1.12.955.3

**Comment by sealj553** [comment]
I also have this issue with Chromium Version 61.0.3163.91 (Developer Build) (64-bit)

**Comment by iori3000** [comment]
It works again now, recent 62.0.3202.62 (64bit)

**Comment by entdark** [comment]
Smooth Scroll 1.6.1, Chrome 61.0.3163.100
Home does not work.

**Comment by jhlee8804** [comment]
+1

**Comment by Inversion-des** [comment]
Home does not work. Only Ctrl+Home helps to jump to the top.

**Comment by gblazex** [comment]
fixed
