### ISSUE TITLE
 scroll-behavior: smooth causes to lag an extension

### ISSUE THREAD

**Issue by Yanpas** [gblazex/smoothscroll#162]
Test page `https://nodejs.org/en/docs/` has the following xss section which causes cery slow scrolling:
```
html {
    scroll-behavior: smooth
}
```

After removing it scrolling is fast again

**Comment by ledlamp** [comment]
Same issue; on nodejs.org scrolling is very slow. I don't see what the `scroll-behavior: smooth` does cause without the extension the site scrolls un-smoothly like any other site.

**Comment by ledlamp** [comment]
Also reproduceable with the demo at https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

It's like the scrolling is locked and it only can move one pixel either way. In the wrong direction.

**Comment by dagmost** [comment]
Same issue on archdaily.com.

**Comment by gblazex** [comment]
fixed in the latest version
