### ISSUE TITLE
Smoothscroll overlapping with native scrolling 

### ISSUE THREAD

**Issue by oomek** [gblazex/smoothscroll#181]
Something weird happened recently.
in Version 73.0.3683.27 (Official Build) beta (64-bit) of Chrome your addon is fighting with the native Chrome's scrolling. When in chrome flags smooth scrolling is enabled I get jerky scrolling. when this flag is disabled I get sudden initial jump and then smoothscroll takes over.

**Comment by misternop** [comment]
Can confirm. Scrolling is very jerky, for every scroll event via mouse wheel there is a initial jump and then smooth scrolling tail.

This doesn't happen for keyboard scrolling. Only mouse wheel.

**Comment by Csokis** [comment]
Same with 73.0.3683.75 stable! :(

**Edit:** Move the mouse cursor to the right of the scrollbar, and scroll. Works perfectly! :O WTF?!

**Comment by gblazex** [comment]
fixed in latest version
