### ISSUE TITLE
Middle mouse click scrolling very slow scrolling

### ISSUE THREAD

**Issue by ghost** [gblazex/smoothscroll#183]
I just discovered that when a website uses "scroll-behavior: smooth;" (https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) it will scroll very very slow when using middle mouse scrolling.

Example:

https://www.html-seminar.de/css-scroll-behavior-smooth.htm
https://www.w3schools.com/howto/howto_css_smooth_scroll.asp

I'm using SmoothScroll 1.6.17 with the IE profile.

**Comment by gblazex** [comment]
i can reproduce this

**Comment by gblazex** [comment]
fixed in latest
