### ISSUE TITLE
Disabling middle mouse scrolling doesn't work

### ISSUE THREAD

**Issue by ghost** [gblazex/smoothscroll#184]
Simply put, when I uncheck the "Enable middle mouse scrolling" checkbox and click "Save", SmoothScroll is still activated for the middle mouse scroll wheel of my mouse. If I disable the extension, the middle mouse scroll returns to how I'd like it to work.

**Comment by gblazex** [comment]
middle mouse scrolling options is for clicking and holding the middle mouse button.

turning the scroll wheel is always smoothed by the extension, that is its sole purpose.
