### ISSUE TITLE
Scrolling distance is increased drastically until button is clicked. Bug?

### ISSUE THREAD

**Issue by Linuspogo** [gblazex/smoothscroll#187]
Hi,
I have encountered the issue in Chrome that after scrolling for some time, the scroll distance is increased drastically (e.g. half a page with one mouse-wheel increment), until a button is clicked; then it is reset to the correct value. I think that this is related to this extension, because I did not encounter it after turning it off. 
I noticed that the scroll distance is also not the same when simply scrolling up and down with single mouse-wheel increments on any given page. Should this not always be the same distance?
Experienced with MX Master as well as MX Master 3.

**Comment by gblazex** [comment]
havent heard of this issue

**Comment by KragV** [comment]
Same issue here, moving the cursor around usually resets the scrolling increment to default.
It doesn't scroll half a page for me but it does seem to at least double the scroll distance each time this effect happens, and it does happen all the time. 
I didn't notice it until today and I've been using the extension for years.

**Comment by Linuspogo** [comment]
> Same issue here, moving the cursor around usually resets the scrolling increment to default.
> It doesn't scroll half a page for me but it does seem to at least double the scroll distance each time this effect happens, and it does happen all the time.
> I didn't notice it until today and I've been using the extension for years.

You are right, I never noticed it but moving the cursor does indded fix it, not only clicking as I stated above! So this seems to be the same issue. However, it also happened for me now with smoothscroll deactivated, so I guess it is not related to that extension. I will close the issue.
