### ISSUE TITLE
Horizontal Gesture History navigation not working

### ISSUE THREAD

**Issue by raphtlw** [gblazex/smoothscroll#188]
This is so smooth on a PC especially on a gaming mouse, but wierdly, the horizontal gesture navigation seems to be not working anymore, even when I try doing alt+left it still doesn't navigate to the previous page. Great work on the extension though! By the way, this is happening on Windows 10 Home, Chrome version 77 on a Microsoft Surface Laptop 2.

**Comment by gblazex** [comment]
what is alt+left? can yo describe more?

**Comment by raphtlw** [comment]
In short, this extension makes the keyboard shortcut Alt+Left arrow useless.

**Comment by gblazex** [comment]
That sounds odd as smoothscroll doesn't do anything if any modifier key is pressed 
(ctrl, alt, shit)

https://github.com/gblazex/smoothscroll/blob/master/src/sscr.js#L409-L410

https://github.com/gblazex/smoothscroll/blob/master/src/sscr.js#L429-L430

**Comment by raphtlw** [comment]
I don't know but I disabled all the extensions and tested it, but it doesn't seem to be compatible with the keyboard shortcuts for horizontal navigation.

**Comment by gblazex** [comment]
I just checked and the extension doesn’t affect ALT + Arrow nav 


Blaze

**Comment by raphtlw** [comment]
Okay, thanks for the replies. I'll try it out again to see if it still affects alt + arrow on my side.
