### ISSUE TITLE
If the price can be cheaper?

### ISSUE THREAD

**Issue by AYiXi** [gblazex/smoothscroll#194]
Like title says, it is a little expensive in Chinese, I very like this soft but cant afford it.
And, whether can offer a life-term useage?

**Comment by jtbrown3** [comment]
I also concur,  Way too expensive for a utility of this type.  I'd suggest offering a lifetime license at an affordable price of $19.95 (in addition to a 1 year for $9.99).   The additional volume of new-user sales will bring in enhanced revenue over the current pricing (IMHO).

**Comment by gblazex** [comment]
message the support email about possible discounts
