### ISSUE TITLE
Excluded pages exclude bilibilibili. Com does not take effect, pressing the space will trigger the scrolling screen

### ISSUE THREAD

**Issue by miniKoala** [gblazex/smoothscroll#213]
title

**Comment by miniKoala** [comment]
![image](https://user-images.githubusercontent.com/107685921/176981225-fa8a16ac-bc3f-47fe-847d-39a358ad66f7.png)

**Comment by chenzongshun** [comment]
油猴脚本亲测可用

    window.onload = function () {
        document.onkeydown = function (event) {

            // 按下空格时，禁用滚动屏幕事件
            if (event.keyCode == 32) {
                event.returnValue=false;
            }
        }
    };
