### ISSUE TITLE
Scrolling will not be smooth enough

### ISSUE THREAD

**Issue by cmhdream** [gblazex/smoothscroll#214]
chrome version
109.0.5414.75 x64

[Chromium Wheel Smooth Scroller](https://chrome-stats.com/d/khpcanbeojalbkpgpmjpdkjnkfcgfkhb)
This kit is so much smoother.
The setting is also simple and clear.

**Comment by gblazex** [comment]
They both link to display refresh rate. There can be no difference in smoothness

as for the settings be simpler there I agree
