### ISSUE TITLE
I can't scroll through short videos on youtube.

### ISSUE THREAD

**Issue by ymtymt** [gblazex/smoothscroll#218]
I can't scroll through short videos on youtube.

**Comment by gblazex** [comment]
At all?

**Comment by ymtymt** [comment]
![無題](https://user-images.githubusercontent.com/116521677/219014423-9df52e88-2b65-4582-9475-e029ab6f22c4.png)
 yes.
Scrolls rarely when moved up and down violently.

**Comment by gblazex** [comment]
fixed in latest i believe

comment if not 

(wait for review to go through)
