### ISSUE TITLE
Mouse wheel scrolling doesn't seem to work on some pages

### ISSUE THREAD

**Issue by KylinZhangQAQ** [gblazex/smoothscroll#220]
For example, in the https://js.design/community?category=explore page, scrolling seems to be disabled,It greatly affects the experience of web browsing, but it is still the best plug-in I have ever used.

**Comment by day-trippr** [comment]
I have run into this problem. W10P x64 22H2 Chrome Version 114.0.5735.134 (Official Build) (64-bit)
Easiest way to duplicate it: launch Chrome, search for "random images", then click on the Images filter. 
The resulting page of images cannot be scrolled with this Smooth Scrolling extension enabled.

Cheers!

**Comment by Spaccce** [comment]
I am experiencing this problem too

**Comment by gblazex** [comment]
i tested both things and it works for me as of today
