### ISSUE TITLE
"Step size" option doesn't work after i alter it

### ISSUE THREAD

**Issue by skxmxm** [gblazex/smoothscroll#221]
I try to change the "step size" but found it still the same. But "Arrow key step size" can be changed succesfully. Seems like the "step size" is always set to "100" no matter how i change it.
I use edge as my brower and logitech g502x as my mouse.

**Comment by cmhdream** [comment]
you can try this new app. working for me great.
https://www.desksoft.com/ScrollNavigator.htm

**Comment by cmhdream** [comment]
Check box
=================
Tick ​​ 		- true
Blank 		- false
Solid black 	- does not set


Parameter value
=================
Black font - Changes and settings Parameter values
Gray font - does not change the main program settings
