### ISSUE TITLE
Breaks site with header which auto-disappers on scroll

### ISSUE THREAD

**Issue by d9k** [gblazex/smoothscroll#222]
Try to scroll these pages with and without Smoothscroll extension enabled:

- https://mantine.dev/app-shell/?e=Headroom
- https://mantine.dev/hooks/use-headroom/

Used extension settings:

<img src="https://github.com/gblazex/smoothscroll/assets/7331988/b83aee37-d8de-4c32-a66f-9f374bb19c8d" height="800">

**Comment by gblazex** [comment]
cannot reproduce
