### ISSUE TITLE
Vertical scroll bug in Notepad++

### ISSUE THREAD

**Issue by Enlight432** [gblazex/smoothscroll#224]
Vertical scrolling in Notepad++ has a bug, in other words, it scrolls very badly
please solve this problem
and if anyone knows a trick to solve this problem, it will be appreciated.

If you need a record from Notepad ++ to solve the problem, tell me and I will record it for you

**Comment by gblazex** [comment]
hey

unfortunately it is not possible to solve. They are using very old windows renderer.
