### ISSUE TITLE
keyoard support interfers with 'copilot.microsoft.com'

### ISSUE THREAD

**Issue by artifact4727** [gblazex/smoothscroll#225]
space key doesn't work on 'copilot.microsoft.com' when keyoard support is enabled, thanks

**Comment by caeldom** [comment]
FYI disabling keyboard support also temp fixes the spacebar issue when trying to type a space into the searchbar at the top of [Reddit](https://www.reddit.com/).

**Comment by gblazex** [comment]
fixed in latest
