### ISSUE TITLE
[Question] smoothscroll program or smoothscroll extension for Google Chrome #107

### ISSUE THREAD

**Issue by Enlight432** [gblazex/smoothscroll#226]
Hello Friends
Sorry if my question is beginner
which one is better for Google Chrome? Currently, both are active, that is, I did not disable Google Chrome from within the program and I did not disable the Google Chrome extension from Google Chrome, and I do not feel a problem, but I said to ask to make sure that I am not doing something wrong, thanks

**Comment by gblazex** [comment]
hey

the native program is enough alone

it should work on all websites (the extension has more limitations)

**Comment by Enlight432** [comment]
@gblazex
But the extension causes the smooth scrolling page down page up, and the arrows (smooth scrolling of the keyboard).
I don't want to lose these two features
