### ISSUE TITLE
SmoothScroll disables SPACEBAR on MS Copilot

### ISSUE THREAD

**Issue by F0RMATTED** [gblazex/smoothscroll#227]
Really weird issue but if you are using Microsoft Copilot with SmoothScroll installed the spacebar will simply not work on the entire webpage of https://copilot.microsoft.com/
Putting the page in the exclusion list solves the issue but... wtf.

**Comment by caeldom** [comment]
I also experienced the same issue trying to type into the searchbar at the top of [Reddit](https://www.reddit.com/), spacebar won't insert space and will scroll the page instead. I found a temporary fix, you can try disabling Features > Enable keyboard support in SmoothScroll settings and see if that fixes the spacebar issue for you!

**Comment by gblazex** [comment]
fixed in latest
