### ISSUE TITLE
The extension causes the spacebar to stop working in Chrome

### ISSUE THREAD

**Issue by lesseranteater** [gblazex/smoothscroll#228]
Hi,

When the extension is active in Chrome I can no longer input an interval with the spacebar in the question text area on the following site:

https://copilot.microsoft.com/

The problem has been reported by other users on Reddit:

https://www.reddit.com/r/chrome/comments/1be88jc/spacebar_not_typing_space_on_specific_websites/

Regards,
LA

**Comment by caeldom** [comment]
I am also experiencing the same issue trying to type into the searchbar at the top of [Reddit](https://www.reddit.com/), spacebar won't insert space and will scroll the page instead. I found a temporary fix, you can try disabling `Features > Enable keyboard support` in SmoothScroll settings and see if that fixes the spacebar issue for you!

**Comment by gblazex** [comment]
fixed in latest
