### ISSUE TITLE
Smoothscroll prevents using spacebar on reddit

### ISSUE THREAD

**Issue by hlvrn** [gblazex/smoothscroll#229]
Oddly, smoothscroll prevents using spacebar on reddit. Youcannotusespacesanymore - in other words. It's only on reddit.

There are other people having the same issue: https://www.reddit.com/r/chrome/comments/1be88jc/spacebar_not_typing_space_on_specific_websites/

Browser: Edge, latest version
Windows 11

Disabling smoothscroll completely, not just excluding reddit as a site, did the trick. Can this be looked into?

**Comment by ez2remember** [comment]
Came here to post this. So infuriating!

**Comment by gblazex** [comment]
fixed in latest
thanks for reporting guys
