### ISSUE TITLE
Scrolling becomes disabled on certain sites

### ISSUE THREAD

**Issue by Eldaw** [gblazex/smoothscroll#73]
When Smoothscroll is enabled, scrolling with the mousewheel or keyboard becomes impossible on certain pages/sites, e.g. the pages under the 'Menu' dropdown at mega.co.nz. Try this page for example:

https://mega.co.nz/#blog

Mousewheel and arrow keys do nothing. The only way to scroll is by dragging the slider on the scrollbar.

**Comment by Szymon-dziewonski** [comment]
i found out that when mouse is over input or textarea you cant use mousewheel, it just stuck - use have to w8 1-2 second to use it again

**Comment by galambalazs** [comment]
@Szymon-dziewonski  What operating system / chrome version?

**Comment by Szymon-dziewonski** [comment]
windows 8.1 , chrome 42.0.2311.90 m

**Comment by galambalazs** [comment]
That website must do something fishy.

Input and textarea elements should work fine: http://jsbin.com/duxaviluwo

I may look into that particular case when I have some free time but seems like an edge case to me (probably the website's fault).

**Comment by galambalazs** [comment]
Do you have other pages where you had this problem?

**Comment by Szymon-dziewonski** [comment]
nope, I used your plugin few times and its perfect, never had problem just here, I figure it out that inputs and textarea doing this freeze, I disable all js on that page just left plane html input there and thats it, so thought you might know :)

**Comment by galambalazs** [comment]
Yes thanks for the input!

 I try to be conservative with edge cases like that, because the code I might add to deal with it can break other websites (which then makes it not worth it).

**Comment by Szymon-dziewonski** [comment]
No problem hope it could help you to improve your great work

2015-04-21 12:10 GMT+02:00 Balázs Galambosi <notifications@github.com>:

> Yes thanks for the input!
>
> I try to be conservative with edge cases like that, because the code I
> might add to deal with it can break other websites (which then makes it not
> worth it).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galambalazs/smoothscroll/issues/73#issuecomment-94729712>
> .
>



-- 
--------------------------
Pozdrawiam,
Szymon Dziewoński

www.szymondziewonski.com
<http://www.szymondziewonski.com>

**Comment by Szymon-dziewonski** [comment]
I found out why it is happening it has nothing to do with inputs, I had doubts afte that and I found its because of scroll isnt on body but wrap and there is body > #outer-wrap > #inner-wrap
and style to it 
`<body{
    overflow: hidden;
}
#outer-wrap{
    width: 100%;
    height: 100%;
    overflow: auto;
    position: absolute;
}
#outer-wrap #inner-wrap{
    width: 100%;
}>`

 and the script breaks on random inputs textareas and anchors also

**Comment by ZarrocTheBlade** [comment]
Google Music's new update broke the scrolling. 
For reference https://play.google.com/music/listen

**Comment by galambalazs** [comment]
yes some people reported this and I looked into it.

Google Music is using Polymer elements (like core-header-panel) which don't expose the scrollTop property. I don't know how to deal with this yet (other than put those elements on a blacklist perhaps).

They basically act as a black whole hiding all scroll data.

**Comment by galambalazs** [comment]
@Szymon-dziewonski can you put up a simple test page of your case to jsbin.com or jsfiddle.com ?

**Comment by galambalazs** [comment]
@ZarrocTheBlade I added Google Music to a blacklist for now.

**Comment by Szymon-dziewonski** [comment]
Im gonna try to recreate issue

**Comment by galambalazs** [comment]
new find http://www.kreydle.com/

**Comment by misternop** [comment]
New broken site http://www.makeuseof.com/

Also your last site kreydle can at least be scrolled with middle mouse button universal scroll. This one can't even that. 

About Eldaw's reported https://mega.co.nz/#blog at least for me scrolling works but addon seems to disable itself - there is no smooth scrolling.

**Comment by derekpock** [comment]
This happens when the website captures the scroll and cancels the default event using event.preventDefault(). Here is a simple html file showing this effect. Try scrolling with the plugin enabled, and any effects will be cancelled by the javascript.

Note: Git doesn't support uploading html files, so change the "txt" extension to "html" when you download it, or you can just view it if you want.


[index.txt](https://github.com/galambalazs/smoothscroll/files/301633/index.txt)

**Comment by gblazex** [comment]
all these sites work for me now

 http://www.ip-finder.me/
https://mega.co.nz/#blog 
http://www.makeuseof.com/
