### ISSUE TITLE
Leave my scrolling alone…

### ISSUE THREAD

**Issue by coreyward** [gblazex/smoothscroll#85]
The premise of “smoothscroll” should not be to fuck up my OS native scrolling, which is buttery smooth and consistent across all applications. I don't have a mousehweel. I have a trackpad and a touch sensitive mouse that, just like a touch screen device, allows me to scroll in varying increments at whatever speed I'd like very naturally. Smoothscroll fucks that all up, misinterpreting what I want and scrolling me faster and further than I expect. 
### Bug: Unexpected Behavior

When the smoothscroll library is employed, web page scrolling no longer behaves according to the system settings and fails to cater to the experience a user is desiring. 
### Solution: Remove the `src` directory.

By removing the `src` directory from the library the bug is resolved. No known side effects are introduced.

I'll happily submit a pull request to resolve the issue if desired.

**Comment by ldexterldesign** [comment]
+1 ~ https://twitter.com/ldexterldesign/status/952883288888299520
