### ISSUE TITLE
Wrong layout on some websites

### ISSUE THREAD

**Issue by elchiapp** [gblazex/smoothscroll#94]
I wrote "on some websites" because I'm sure this is not the only case.

Try going to https://gofuckingdoit.com/ . You will see the upper section is completely covered by the pictures with different objectives (e.g. "Go to China" etc.).

This doesn't happen if you disable the smoothscroll extension (or go incognito).

Thanks for your time.
- Screenshots *

Correct layout:
![screenshot 6](https://cloud.githubusercontent.com/assets/1369747/3752344/eef038e8-1806-11e4-8374-b47b26c00286.png)

Incorrect layout:
![screenshot 7](https://cloud.githubusercontent.com/assets/1369747/3752351/0c8570bc-1807-11e4-9d97-c11b150826f9.png)

**Comment by galambalazs** [comment]
@Ciantic extra empty space was fixed in the latest version :-) cheers
